[build]
  publish = "dist"
  command = "npm run build"
  ignore = "git log -1 --pretty=format:'%ae' | grep -v 'bcanata@hotmail.com'"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
