[build]
  publish = "dist"

[context.production.environment]
  NETLIFY_SITE_URL = "https://taslak.radio.org.tr"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/decapcms/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[redirects]]
  from = "/#confirmation_token=*"
  to = "/auth?confirmation_token=:splat"
  status = 200

[[redirects]]
  from = "/#recovery_token=*"
  to = "/auth?recovery_token=:splat"
  status = 200

[[redirects]]
  from = "/#invite_token=*"
  to = "/auth?invite_token=:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/decapcms/index.html"
  status = 200