[build]
  publish = "dist"

[[redirects]]
  from = "/#confirmation_token=*"
  to = "/auth?confirmation_token=:splat"
  status = 200

[[redirects]]
  from = "/#recovery_token=*"
  to = "/auth?recovery_token=:splat"
  status = 200

[[redirects]]
  from = "/#invite_token=*"
  to = "/auth?invite_token=:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/decapcms/index.html"
  status = 200