backend:
  name: git-gateway
  branch: main
  accept_roles:
    - admin
    - editor
  squash_merges: true

local_backend: true

media_folder: 'src/assets/images'
public_folder: '/images'

locale: 'tr'

site_url: https://radio.org.tr
display_url: https://radio.org.tr

collections:
  - name: 'post'
    label: 'Blog Yazıları'
    folder: 'src/data/post'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Başlık'
        name: 'title'
        widget: 'string'
      - label: 'Yayın Tarihi'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD HH:mm:ss'
      - label: 'Yazar'
        name: 'author'
        widget: 'string'
        default: 'TA1SPH'
      - label: 'Kategoriler'
        name: 'categories'
        widget: 'list'
        allow_add: true
        allow_delete: true
        collapsed: false
        field:
          label: 'Kategori'
          name: 'category'
          widget: 'string'
      - label: 'Etiketler'
        name: 'tags'
        widget: 'list'
        allow_add: true
        allow_delete: true
        collapsed: false
        field:
          label: 'Etiket'
          name: 'tag'
          widget: 'string'
      - label: 'Düzen'
        name: 'layout'
        widget: 'string'
        default: 'post'
      - label: 'Öne Çıkan Görsel'
        name: 'image'
        widget: 'image'
        required: false
      - label: 'İçerik'
        name: 'body'
        widget: 'markdown'